import {
  Smartphone,
  Monitor,
  Headphones,
  Watch,
  Camera,
  Gamepad2,
  Laptop,
  Tablet,
  Speaker,
  Keyboard,
  Mouse,
  Printer,
  Router,
  HardDrive,
  MemoryStick,
  Cpu,
  MonitorSmartphone,
  SmartphoneCharging,
  Wifi,
  Bluetooth,
  Package,
} from 'lucide-react'
export const categoryIcons: Record<string, React.ElementType> = {
  electronics: Monitor,
  smartphones: Smartphone,
  laptops: Laptop,
  tablets: Tablet,
  accessories: Headphones,
  gaming: Gamepad2,
  cameras: Camera,
  smartwatches: Watch,
  audio: Speaker,
  peripherals: Keyboard,
  networking: Router,
  storage: HardDrive,
  components: Cpu,
  mobile: MonitorSmartphone,
  charging: SmartphoneCharging,
  wireless: Wifi,
  bluetooth: Bluetooth,
  memory: MemoryStick,
  input: Mouse,
  printing: Printer,
  clothing: Package,
  footwear: Package,
  shoes: Package,
  furniture: Package,
  books: Package,
  watches: Watch,
  headphones: Headphones,
  speakers: Speaker,
  keyboards: Keyboard,
  mousepads: Mouse,
}
