import authRoutes from '@/modules/auth/auth.route';
import userRoutes from '@/modules/user/user.routes';
import addressRoutes from '@/modules/address/address.routes';
import logRoutes from '@/modules/logs/logs.route';
import categoryRoutes from '@/modules/category/category.route';
import productRoutes from '@/modules/product/product.route';
import ReviewRoutes from '@/modules/review/review.routes';
import variantRoutes from '@/modules/variant/variant.route';
import attributeRoutes from '@/modules/attribute/attribute.route';
import cartRoutes from '@/modules/cart/cart.routes';
import orderRoutes from '@/modules/order/order.routes';
import analyticsRoutes from '@/modules/analytics/analytics.routes';
import { configureChatRoutes } from '@/modules/chat/chat.route';
import { Router } from 'express';
import { Server as WebsocketServer } from 'socket.io';

export const ConfigureV1Routes = (io: WebsocketServer) => {
  const router = Router();
  router.use('/auth', authRoutes);
  router.use('/user', userRoutes);
  router.use('/address', addressRoutes);
  router.use('/auth', authRoutes);
  router.use('/logs', logRoutes);
  router.use('/categories', categoryRoutes);
  router.use('/products', productRoutes);
  router.use('/reviews', ReviewRoutes);
  router.use('/variants', variantRoutes);
  router.use('/attributes', attributeRoutes);
  router.use('/cart', cartRoutes);
  router.use('/orders', orderRoutes);
  router.use('/analytics', analyticsRoutes);
  router.use('/chat', configureChatRoutes(io));
  return router;
};
