import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import MainLayout from '@/components/templates/MainLayout'
import ClientProviders from '@/providers/ClientProvider'
import { ApolloWrapper } from '@/lib/apollo/wrapper'
import Toast from '@/components/feedback/Toast'
const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Modern Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ClientProviders>
          <ApolloWrapper>
            <MainLayout>
              {children}
              <Toast />
            </MainLayout>
          </ApolloWrapper>
        </ClientProviders>
      </body>
    </html>
  )
}
