import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import MainLayout from '@/components/templates/MainLayout'
import Provider from '@/providers/ClientProvider'
const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Modern Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Provider>
          <MainLayout>{children}</MainLayout>
        </Provider>
      </body>
    </html>
  )
}
